"""add target_date to goals

Revision ID: 44e016b71961
Revises: 43bf1e1e4eef
Create Date: 2026-03-24 15:36:42.622403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e016b71961'
down_revision: Union[str, Sequence[str], None] = '43bf1e1e4eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('target_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'target_date')
    # ### end Alembic commands ###
